version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: esg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: esg
      POSTGRES_PASSWORD: esg
      POSTGRES_DB: esg_reporter
    ports:
      - '5432:5432'
    volumes:
      - esg_pgdata:/var/lib/postgresql/data

volumes:
  esg_pgdata:
